### ISSUE TITLE
Remove dist/ directory from Git repository?

### ISSUE THREAD

**Issue by timabbott** [zulip/github-actions-zulip#11]
Unless the GitHub Actions model somehow requires it, we probably don't want to have a large generated file in the Git repository.

**Comment by ggrossetie** [comment]
@timabbott as far as I know, it's required by the GitHub Actions model. See: https://github.com/actions/javascript-action where `dist` is versioned.

GitHub Actions ignores `index.js` and uses `dist/index.js`.

**Comment by andersk** [comment]
Yeah, this is how GitHub Actions works.
