### ISSUE TITLE
Take list of users as a YAML list of strings or numbers, rather than doing string parsing

### ISSUE THREAD

**Issue by andersk** [zulip/github-actions-zulip#13]
The `to: '9'` syntax is silly; that should be `to: [9]`. We should not need to use regexes to figure out whether the input looks numeric, because YAML already gives us that information.

**Comment by ggrossetie** [comment]
That what I had in mind but `getInput` from [`@actions/core`](https://github.com/actions/toolkit/blob/e76decaf8a52bc981d17ddd3efcca548f6bc1a0e/packages/core/src/core.ts#L84-L92) returns a string... but maybe there's another way to retrieve input values?

**Comment by ggrossetie** [comment]
@andersk Could you please elaborate on what you had in mind? Am I missing something or is it a limitation we will have to live with?

**Comment by ggrossetie** [comment]
Closing, feel free to reopen with additional information on how we could improve things.
