### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by ggrossetie** [zulip/github-actions-zulip#16]
Currently, I'm using my personal account on one of my Zulip organization to test this GitHub Actions (using GitHub Actions!): 

https://github.com/zulip/github-actions-zulip/blob/2abd9514596ae2e1130fa89ed1ef51d997cce2d1/.github/workflows/local-test.yml#L22-L40

Unfortunately, I cannot configure secrets on this repository so `api-key` is undefined and tests are failing:

https://github.com/zulip/github-actions-zulip/blob/2abd9514596ae2e1130fa89ed1ef51d997cce2d1/.github/workflows/local-test.yml#L26

@timabbott Do you think it would be possible to setup/use a test organization to test this GitHub Actions?

**Comment by ggrossetie** [comment]
I found an interim solution to disable integration tests when the secret is not available.

**Comment by timabbott** [comment]
I created a test organization on zulipchat.com; can you join via this link?  

https://github-actions-test.zulipchat.com/join/6qum44zsz7n7k34ojm4yzhai/

You can then make a bot and configure its API key for testing this using that organization.

**Comment by ggrossetie** [comment]
@timabbott Thanks for creating this organization. I cannot configure secrets on this repository. How should we proceed?

**Comment by timabbott** [comment]
@Mogztter sorry for the slow reply; it's been a very busy few weeks.  I've added admin access for you to this repository; as its maintainer you should have that in any case, and that should let you configure the integration.
