### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by SeanTAllen** [zulip/github-actions-zulip#28]
Can you tag a new release for this?

**Comment by ggrossetie** [comment]
We are working on it.
We will release a new version when the migration (to the zulip organisation)  is completed.

**Comment by timabbott** [comment]
@Mogztter is the main thing we want here before a release getting the automated tests running?

**Comment by ggrossetie** [comment]
> is the main thing we want here before a release getting the automated tests running?

No, the last remaining item is https://github.com/zulip/github-actions-zulip/issues/12. I was unwilling to release a new version until we have the right naming and directory structure but I think we now have a clear path forward.

We should probably release version 1.0.0 to make it clear that this is a major bump (i.e., the action was renamed and a few parameters were removed/updated)

**Comment by timabbott** [comment]
That plan sounds good.  (I think the other option was to release what we had as 0.2 or whatever and defer the 1.0, but I agree it'd be better to just get that done!).

**Comment by ggrossetie** [comment]
@timabbott @andersk I think we are good to go for the v1.0.0 release (and `v1` alias). Is there any objection or things we should do before that?

**Comment by timabbott** [comment]
Sounds good to me!

**Comment by ggrossetie** [comment]
@timabbott I don't think I have the permission to publish a new version on the marketplace. I've created a new version: https://github.com/zulip/github-actions-zulip/releases/tag/v1.0.0 but GitHub didn't ask me to publish it to the marketplace.

**Comment by timabbott** [comment]
I am not offered an option to publish to marketplace on that page either!

**Comment by ggrossetie** [comment]
@timabbott I think you need to draft/create a new release: https://github.com/zulip/github-actions-zulip/releases/new

You should see:

![new-release](https://user-images.githubusercontent.com/333276/129759826-4784fc6d-fd00-4519-b568-47fb9d9f47bf.png)

No?

**Comment by ggrossetie** [comment]
Or maybe we actually need a dummy `action.yml` at the root of the project... not sure 🤔

**Comment by ggrossetie** [comment]
From GitHub documentation:

> Actions are published to GitHub Marketplace immediately and aren't reviewed by GitHub as long as they meet these requirements:
> * The action must be in a public repository.
> * **Each repository must contain a single action.**
> * **The action's metadata file (action.yml or action.yaml) must be in the root directory of the repository.**
> * The name in the action's metadata file must be unique.
>    * The name cannot match an existing action name published on GitHub Marketplace.
>    * The name cannot match a user or organization on GitHub, unless the user or organization owner is publishing the action. For example, only the GitHub organization can publish an action named github.
>    * The name cannot match an existing GitHub Marketplace category.
>    * GitHub reserves the names of GitHub features.

https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

GitHub CodeQL actions are not published on the Marketplace (or, at least, I cannot find them), so I don't think it's a good example to follow.
In the end, using a subdirectory was probably a bad idea 😞 

So, what should we do?

**Comment by andersk** [comment]
[chat.zulip.org discussion](https://chat.zulip.org/#narrow/stream/127-integrations/topic/GitHub.20Actions/near/1248815)

**Comment by Zharktas** [comment]
Can the release of newer versions to marketplace be advanced to somewhere ? Github actions already warn that nodejs12 is deprecated and this action will fail on summer 2023 when node12 is removed all together

**Comment by klardotsh** [comment]
For now, using `uses: zulip/github-actions-zulip/send-message@v1.0.1` (or just `@v1`, [as we do in zulip/zulip](https://github.com/zulip/zulip/blob/ecead64718d2b74ded21323791eec85b56e1c5c4/.github/workflows/zulip-ci.yml#L243)) should work around the deprecation issue while awaiting the Marketplace update.

**Comment by pbrisbin** [comment]
> For now, using uses: zulip/github-actions-zulip/send-message@v1.0.1 (**or just @v1, [as we do in zulip/zulip](https://github.com/zulip/zulip/blob/ecead64718d2b74ded21323791eec85b56e1c5c4/.github/workflows/zulip-ci.yml#L243)**) should work around the deprecation issue

The bolded part is not true. While the v1.0.1 tag is using node16 now, [the v1 tag is behind](https://github.com/zulip/github-actions-zulip/compare/v1...v1.0.1).

Can you please advance the v1 tag so using `@v1` gets the latest v1 release (v1.0.1) as expected?
