### ISSUE TITLE
Should the `api-key` field be a secret?

### ISSUE THREAD

**Issue by tisonkun** [zulip/github-actions-zulip#46]
If so, you can update the document to prevent users hardcode this key.

**Comment by timabbott** [comment]
Yes, API keys should of course be secret.  Can you be more concrete about what you have in mind here?

**Comment by timabbott** [comment]
Ahh, I see; yeah the documentation doesn't highlight that one should use the GitHub Actions secret system.

@Mogztter do you have time to tweak this?
