### ISSUE TITLE
Align the interface with Zulip's send-message API

### ISSUE THREAD

**Issue by timabbott** [zulip/github-actions-zulip#6]
https://zulip.com/api/send-message documents our send-message API; https://zulip.com/api/configuring-python-bindings explains how we format `zuliprc` files.  We should align the names for variables between the GitHub Action and what we document in the API, since it's an arbitrary choice and we might as well be consistent.

**Comment by timabbott** [comment]
One note here is that we might want to change Zulip's API bindings to use `organization_url` rather than `site`, so I'd be tempted to leave the `organization_url` name as is (aside from a `-` to `_` conversion, which is probably a good idea).

**Comment by ggrossetie** [comment]
GitHub Actions is (mostly) using kebab case: `continue-on-error`, `runs-on`... having said that I'm fine with snake case as long as we stay consistent

**Comment by ggrossetie** [comment]
> aside from a - to _ conversion, which is probably a good idea

I think it's a good idea to use the same terminology but not necessarily the same casing. Snake case is extremely common (recommended?) in Python environments but less common in other languages/formats.

Here's what I intend to do:

| Zulip API | GitHub Action | Action |
| -- | -- | -- |
| `email` | `username` | Rename `username` to `email` |
| `key` | `api-key` | `key` is a bit vague, I think we should keep `api-key` |
| ` ` | `password` | Remove 🗑️ |
| `site` | `organization-url` | I think we should keep `organization-url` |
| `to` | `to` | - |
| `type` | `type` | - |
| `topic` | `topic` | - |
| `content` | `content` | - |

@timabbott Thoughts?

**Comment by timabbott** [comment]
I would prefer to stick with `_` casing, but otherwise agree.  Snake casing is great for any context where something might be a variable name, because most programming languages use `-` for subtraction.  And GitHub's event names are e.g. `pull_request` in an Actions file, so there's going to be plenty of `_`s in those files in general.

(If there's a standard convention that Actions should use `-`s, that'd be a good argument for doing that format despite what I just said, but I'm not aware of such a convention)

**Comment by ggrossetie** [comment]
> If there's a standard convention that Actions should use -s, that'd be a good argument for doing that format despite what I just said, but I'm not aware of such a convention

`pull_request` is an event/variable name not an attribute/property name. Official GitHub Actions (i.e., https://github.com/actions) are using kebab casing:

- https://github.com/actions/checkout
- https://github.com/actions/first-interaction
- https://github.com/actions/stale
- ...

**Comment by timabbott** [comment]
OK, we can go with `-`s for now.  We can presumably change it to support both cases if we change our minds.

**Comment by ggrossetie** [comment]
OK!

@timabbott What do you think about the other suggestions? 

- Rename `username` to `email`
- Remove `password`
- Stick with `api-key`

**Comment by timabbott** [comment]
Yeah, those all sound great!
