### ISSUE TITLE
Add a changelog section to README

### ISSUE THREAD

**Issue by timabbott** [zulip/github-actions-zulip#8]
This will be useful for documenting the API migrations (#6).

**Comment by ggrossetie** [comment]
It's probably better to use a dedicated file (i.e. `CHANGELOG.md`) with a link on the README? What do you think?

**Comment by ggrossetie** [comment]
Alternatively, we could describe changes in the [release note](https://github.com/zulip/github-actions-zulip/releases) since we have to create a new release in order to publish to https://github.com/marketplace?type=actions

**Comment by timabbott** [comment]
I think the "releases" tab approach can work OK, but it's often better to have a separate file, because then you can add notes on what is in master but not released.  But it doesn't super matter; I think what's most important is that the README.md have a link to the changelog so that it's easy to find where we put it.
