### ISSUE TITLE
Add links to Zulip documentation on message formatting, homepage, and other relevant resources

### ISSUE THREAD

**Issue by timabbott** [zulip/github-actions-zulip#9]
The goal here is mainly to help users understand what they need to know in order to understand how to do common custom things (like linking to the formatting documentation so that the user doesn't need to track it down themselves).

This should also make it feel more integrated with the rest of the project.

**Comment by ggrossetie** [comment]
I've added a few links as part of #17

**Comment by ggrossetie** [comment]
I've added a link to the homepage on the README.
[Messages sent via the API](https://zulip.com/api/send-message#parameter-content) (using the `content` parameter) can use [Markdown formatting](https://zulip.com/help/format-your-message-using-markdown)? ? If so, I can add a sentence on the README to make it clear.

> .. and other relevant resources

Anything you would like to add?

**Comment by timabbott** [comment]
Yeah, let's link to https://zulip.com/help/format-your-message-using-markdown in the "Message content" section; I think that's the rest of what I had in mind.
